[package]
name = "buglympics"
version = "1.0.0"
edition = "2018"

[dependencies]
lentsys={path="../../projects/lentsys"}
sdl2="*"

[build-dependencies]
lentsys={path="../../projects/lentsys", features=["io"]}