[package]
name = "buglympics"
version = "1.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lentsys={path="../../projects/lentsys"}

[target.'cfg(not(all(target_arch = "wasm32", target_os = "unknown")))'.dependencies]
sdl2="*"

